### PR TITLE
Nested serialization of Guid with Json serializer.

### LINKED ISSUE #1187: Guid is not properly deserialized in Json serializer.
Seems that ##752 is back again.

When turning on ```UseJsonFormat="true"``` in config - first silo start is working fine, data is nicely saved in json format and all looks good. On consequent runs  - Silo throws Deserialization exception on first encountered stateful grain (in my case it's current UserGrain to check permissions):

```
  "ClassName": "Orleans.Runtime.OrleansException",
    "Message": "Forwarding failed: tried to forward message NewPlacement Request S127.255.0.0:11111:188375097*grn/A5831D15/00000000@4eb809a6->S127.255.0.0:11111:188375097*grn/20286B2F/00000000+095b3cc6f368a382cee5e48bedeff6c7cacd4f30bce8e3d98612e1534363202a@a5c2b583 #47[ForwardCount=2]: global::DBCloud.ActorInterfaces.Users.IUserGrain:GetState() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(GrainState grainState, GrainStateEntity entity)\r\n   at Orleans.Storage.AzureTableStorage.<ReadStateAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Catalog.<SetupActivationState>d__35.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Catalog.<InitActivation>d__2b.MoveNext()",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": null,
    "WatsonBuckets": null
```

### PR DESCRIPTION
**Pull request by gabikliot**
Fixes #1187.

### CODE REVIEW

File: src/Orleans/Serialization/OrleansJsonSerializer.cs [hunk 1]
```diff
@@ -237,5 +233,29 @@ public override object ReadJson(JsonReader reader, Type objectType, object exist
...
+            writer.WriteValue(value.ToString());
+            writer.WriteEndObject();
+        }
+
+        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
+        {
+            JObject jo = JObject.Load(reader);
+            Guid guid = Guid.Parse(jo["Guid"].ToObject<string>());
+            return guid;
+        }
```
Comment (ReubenBond) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: I don't quite understand this change. Could this not be written as:
```C#
public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
{
    if (value == null)
    {
        writer.WriteValue(default(string));
    }
    else if (value is Guid)
    {
        var guid = (Guid)value;
        writer.WriteValue(guid.ToString("N"));
    }
}
public override object ReadJson(
    JsonReader reader, 
    Type objectType, 
    object existingValue, 
    JsonSerializer serializer)
{
    var str = reader.Value as string;
    return str != null ? Guid.Parse(str) : default(Guid);
}
```

I'm missing something.

File: src/Orleans/Serialization/OrleansJsonSerializer.cs [hunk 2]
```diff
@@ -237,5 +233,29 @@ public override object ReadJson(JsonReader reader, Type objectType, object exist
         }
     }
 
+    class GuidConverter : JsonConverter
+    {
+        public override bool CanConvert(Type objectType)
+        {
+            return objectType.IsAssignableFrom(typeof(Guid));
```
Comment (gabikliot) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: `IsAssignableFrom` is the key, and  not `return (objectType == typeof(Guid));`

File: src/Orleans/Serialization/OrleansJsonSerializer.cs (hunk 1 above)
Comment (gabikliot) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: but what converter is it on? The key part is what in function CanConvert. It is applied per type.

Comment (gabikliot) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: The implementation of WriteJson/readJson - there is indeed like 10 different ways it could have been implemented. It is  not my goal to optimize the Json serializer (for Orleans or at all).
I followed up on that issue since it simply did not make sense and kept bothering me. I just could not believe there is no way to have proper Guid deserialization in Json.

And the Json.Net guys [was not helpful](https://github.com/JamesNK/Newtonsoft.Json/issues/762), but he did hint in the past that there is a way - https://github.com/JamesNK/Newtonsoft.Json/issues/728.

File: src/Orleans/Serialization/OrleansJsonSerializer.cs (hunk 2 above)
Comment (ReubenBond) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: I see. Does that support `Nullable<Guid>`?

Comment (ReubenBond) [inline src/Orleans/Serialization/OrleansJsonSerializer.cs]: This is the implementation I've been using, by the way: https://gist.github.com/ReubenBond/9416e7a4c528eab473fd

**Comment by gabikliot** [comment]
Updated to use @ReubenBond's Guid Json converter.

**Comment by jthelin** [comment]
Is this ready to merge now?

**Comment by ReubenBond** [comment]
Yep, LGTM
