### PR TITLE
Fix AsReference() in generated code for null values

### LINKED ISSUE #2750: Having a null grain reference as a property on a GrainState object results in an exception
Having a Grain state object fails to persist if a grain Interface property is unset (`null`)

Solution is to set EventGrainState.Metadata.Owner = to a grain reference.

**Code:**
```csharp
 public class EventGrainState
    {
        public bool IsInitialized { get; set; }
        public ObjectMetadata Metadata { get; set; } = new ObjectMetadata();
        public string Name { get; set; }
        public EventData Data { get; set; } = new EventData();
        public TimeSpan Interval { get; set; }
    }
   public class ObjectMetadata
    {
        public DateTime CreatedDate { get; internal set; }
        public DateTime ModifiedDate { get; internal set; }
        public IUserGrain Owner { get; internal set; }
    }
    public class EventData
    {
        public string EventType { get; set; }
        public string Parameters { get; set; }
    }
```

**Stack Trace:**

```Cannot pass null as an argument to AsReference
Parameter name: grain
   at Orleans.GrainExtensions.AsReference[TGrainInterface](IAddressable grain)
   at NRC.Services.Scheduler.Grains.OrleansCodeGenNRC_Services_Scheduler_Grains_ObjectMetadataSerializer.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at NRC.Services.Scheduler.Grains.OrleansCodeGenNRC_Services_Scheduler_Grains_EventGrainStateSerializer.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.OrleansCodeGenOrleans_GrainStateSerializer`1.DeepCopier(Object original)
   at Orleans.Serialization.SerializationManager.<>c__DisplayClass61_0.<Register>b__0(Object obj)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopierHelper(Type t, Object original)
   at Orleans.Serialization.SerializationManager.DeepCopyInner(Object original)
   at Orleans.Serialization.SerializationManager.DeepCopy(Object original)
   at Orleans.Runtime.GrainReference.InvokeMethodAsync[T](Int32 methodId, Object[] arguments, InvokeMethodOptions options, SiloAddress silo)
   at Orleans.Storage.OrleansCodeGenMemoryStorageGrainReference.WriteStateAsync(String grainType, String grainId, IGrainState grainState)
   at Orleans.Storage.MemoryStorage.<WriteStateAsync>d__21.MoveNext()
```

### PR DESCRIPTION
**Pull request by ReubenBond**
Fix #2750 & #2751

### CODE REVIEW

File: src/OrleansCodeGenerator/SerializerGenerator.cs [hunk 1]
```diff
@@ -595,12 +595,12 @@ public ExpressionSyntax GetGetter(ExpressionSyntax instance, ExpressionSyntax se
...
                     && !typeof(IGrainObserver).IsAssignableFrom(this.FieldInfo.FieldType))
                 {
-                    var getAsReference = getValueExpression.Member(
+                    var getAsReference = getValueExpression.ConditionalMember(
                         (IAddressable grain) => grain.AsReference<IGrain>(),
                         this.FieldInfo.FieldType);
 
                     // If the value is not a GrainReference, convert it to a strongly-typed GrainReference.
-                    // C#: !(value is GrainReference) ? value.AsReference<TInterface>() : value;
+                    // C#: !(value is GrainReference) ? value?.AsReference<TInterface>() : value;
```
Comment (jdom) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: I assume this is just explanatory, but it really doesn't require any c# 6 related tooling in the dev or runtime environment, correct?

Comment (ReubenBond) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: No, it does. Do we still support pre-6?

Comment (jdom) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: *I believe* we support users building their Orleans apps without c#6... Orleans development with pre-6 is not supported.

Comment (jdom) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: but it's not like I tried it or anything since we started using c# 6 features... so maybe I'm under a wrong assumption.

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

File: src/OrleansCodeGenerator/SerializerGenerator.cs (hunk 1 above)
Comment (ReubenBond) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: I don't mind either way. I can change the implementation to perform a manual null check, no worries :)

I'll make the change and submit a revision

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

File: src/OrleansCodeGenerator/SerializerGenerator.cs (hunk 1 above)
Comment (jdom) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: Ah, I missed the update, is the change already done in what's in the branch now?

**Comment by ReubenBond** [comment]
@jdom I've pushed the update - apologies for the delay (was doing SM PR).

Sample of generated code:
```C#
(input.@Writer == null || input.@Writer is global::Orleans.Runtime.GrainReference) ? input.@Writer : input.@Writer.@AsReference<global::UnitTests.GrainInterfaces.IMultifacetWriter>()
```
