### PR TITLE
Fix #852 - record deserialized objects before deserialization has completed

### LINKED ISSUE #852: Bug in DeserializationContext about deserializing cyclic data structures
Issue #843 exposed 2 bugs in the serializer related to cyclic data structures (data structure that has a cycle of references).
The first, minor bug, was related to capturing the right offset during serialization of cyclic data structures. It has been fixed in #851.
The 2nd bug is related to Deserialization.
Currently, when we deserialize an object, we first call its generated deserialization method, which will create an empty object and then recursively call deserialization on its member fields and assign them to the object fields. Only after the object was fully deserialized and created, do we put it in the [`DeserializationContext`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/DeserializationContext.cs#L54). This works if the same object is referenced multiple times from the same parent object (not within a cycle), since when we encounter the same object reference again, it will be found in the [`DeserializationContext`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/DeserializationContext.cs#L60).

However, it does not work for cyclic objects, since when we encounter a 2nd reference to the same object, the parent object (the first reference to that object in the cycle) was not fully deserialized yet (we are currently deserializing it). As a result, it was not put yet in the `DeserializationContext` and thus cannot be found by the 2nd reference.

The suggested fix is to change the order of deserialization and storing of the object in the `DeserializationContext`. We should first allocate a new empty object, then store a reference to it in the `DeserializationContext` and only then recursively call deserialization on its fields. When storing in the `DeserializationContext` we should store at the `var start = stream.CurrentPosition;` offset like done now [here](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/SerializationManager.cs#L1309). The call to `DeserializationContext.Current.RecordObject` will be removed from [`SerializationManager`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/SerializationManager.cs#L1309) and instead moved into the generated serialization code, right after the un-initialized object is created.

### PR DESCRIPTION
**Pull request by ReubenBond**
This fix for #852 is based on @gabikliot's suggestions in that thread.
I have also included @galvesribeiro's tests for that bug. @galvesribeiro's test uses generated code, unlike the existing `SerializationTests_RecursiveSerialization`. I am not sure if the latter should be kept given it needed to be modified to pass the test.

### CODE REVIEW

File: src/Orleans/Serialization/DeserializationContext.cs [hunk 1]
```diff
@@ -27,12 +27,12 @@ MIT License
...
 namespace Orleans.Serialization
 {
-    internal class DeserializationContext
+    public class DeserializationContext
     {
         [ThreadStatic]
         private static DeserializationContext ctx;
 
-        internal static DeserializationContext Current
+        public static DeserializationContext Current
```
Comment (ReubenBond) [inline src/Orleans/Serialization/DeserializationContext.cs]: This is referenced from generated code in order to record the object currently being deserialized.

File: src/Orleans/Serialization/DeserializationContext.cs [hunk 2]
```diff
@@ -47,13 +47,21 @@ private DeserializationContext()
         internal void Reset()
         {
             taggedObjects.Clear();
+            CurrentObjectOffset = 0;
         }
 
+        internal int CurrentObjectOffset { get; set; }
```
Comment (ReubenBond) [inline src/Orleans/Serialization/DeserializationContext.cs]: This is set & reset in `SerializationManager.DeserializeInner`

File: src/Orleans/Serialization/SerializationManager.cs [hunk 3]
```diff
@@ -1366,73 +1366,89 @@ public static T DeserializeInner<T>(BinaryTokenStreamReader stream)
         /// <returns>Object of the required Type, rehydrated from the input stream.</returns>
         public static object DeserializeInner(Type expected, BinaryTokenStreamReader stream)
         {
-            var start = stream.CurrentPosition;
+            var previousOffset = DeserializationContext.Current.CurrentObjectOffset;
+            DeserializationContext.Current.CurrentObjectOffset = stream.CurrentPosition;
 
-            // NOTE: we don't check that the actual dynamic result implements the expected type. We'll allow a cast exception higher up to catch this.
+            try
```
Comment (ReubenBond) [inline src/Orleans/Serialization/SerializationManager.cs]: Most of this code is unchanged, but I wrapped it all in try/finally to ensure that `DeserializationContext.Current.CurrentObjectOffset` is reset.

File: src/OrleansCodeGenerator/SerializerGenerator.cs [hunk 4]
```diff
@@ -193,6 +193,22 @@ private static MemberDeclarationSyntax GenerateDeserializerMethod(Type type, Lis
                             SF.VariableDeclarator("boxedResult").WithInitializer(SF.EqualsValueClause(resultVariable)))));
                 boxedResultVariable = SF.IdentifierName("boxedResult");
             }
+
```
Comment (ReubenBond) [inline src/OrleansCodeGenerator/SerializerGenerator.cs]: The crux of the change: generate code which calls `DeserializationContext.Current.RecordObject` after creating the object being deserialized. Note that we record `boxedResultVariable` in order to handle value types.

File: src/Tester/SerializationTests.cs [hunk 5]
```diff
@@ -143,6 +143,7 @@ public static void Serializer(object untypedInput, Orleans.Serialization.BinaryT
             public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
             {
                 TestTypeA result = new TestTypeA();
+                DeserializationContext.Current.RecordObject(result);
```
Comment (ReubenBond) [inline src/Tester/SerializationTests.cs]: Generated serializers and built-in serializers now record the object before deserialization has completed, so we modify this test to reflect that. This test may be of limited value given @galvesribeiro's test which instead uses generated code.

**Comment by gabikliot** [comment]
Looks good in gene. I can do a detailed code review now.
The previous test has value in that it is standalone, without grains, thus easier to test, repro,  etc... Pure serializer test and not whole system test. Unit test and not integration test, by @Yevhen methodology. No hurm in having both tests I think.

**Comment by gabikliot** [comment]
Meant to write: I can not do a detailed code review now.

**Comment by ReubenBond** [comment]
Thank you, @gabikliot :) I am happy to keep both, too.

**Comment by sergeybykov** [comment]
I'll kick off a functional run with it to see if anything got broken.

**Comment by galvesribeiro** [comment]
Thanks @ReubenBond  :)
