### PR TITLE
Replace DuplicateActivationException with a strongly-typed return value

### LINKED ISSUE #2733: Rename or remove DuplicateActivationException to prevent confusion
`DuplicateActivationException` doesn't mean that a duplicate activation has been created. It is just a means to resolve a race between two or more silos trying concurrently to register activations for the same grain. However, the very name of the exception class and the message of it misleads people to think that they get duplicate activations.

I suggest we rename the exception class to prevent this confusion from happening.

`RegistrationRaceException`? `ActivationAlreadyRegisteredException`? `ExistingActivationException`?

### PR DESCRIPTION
**Pull request by ReubenBond**
This PR resolves #2733.

The fix focuses on the logic in `Catalog.InitActivation(...)` and how it interacts with `Catalog.RegisterActivationInGrainDirectoryAndValidate(...)`. Specifically, it removes the `DuplicateActivationException` thrown by the latter and caught by the former. Doing that required slightly reworking the control flow in `InitActivation` so that exceptions aren't the only means of error handling.

* Move recovery logic in `InitActivation` from `catch` to a new method which is called from the `finally` block.
* Return a new `ActivationRegistrationResult` struct from `RegisterActivationInGrainDirectoryAndValidate` which replaces `DuplicateActivationException`.
* When an activation fails to register, return early from `InitActivation` so that the `finally` block can clean up the activation.

One change worth noting: `InitActivation` will no longer throw when there is a duplicate activation. The activation returned by `GetOrCreateActivation` (which calls into `InitActivation`) will eventually have its `ForwardingAddress` fixed to point to the existing activation. Note that the result of `InitActivation` is only used in one specific case: when creating the `IMembershipTableGrain`. I opened #3129 to discuss converting that into a SystemTarget instead of routing it through the directory.

### CODE REVIEW

File: src/OrleansRuntime/Catalog/Catalog.cs [hunk 1]
```diff
@@ -567,130 +514,176 @@ private void SetupActivationInstance(ActivationData result, string grainType, st
...
+                if (logger.IsVerbose) logger.Verbose("InitActivation is done: {0}", activation.Address);
             }
             catch (Exception ex)
             {
-                lock (activation)
+                // Store and re-throw the exception.
+                exception = ex;
+                throw;
+            }
+            finally
```
Comment (jdom) [inline src/OrleansRuntime/Catalog/Catalog.cs]: why is this in the finally block? Why not both in the catch block as well as in the `if (!registrationResult.IsSuccess)` part?

File: src/OrleansRuntime/Catalog/Catalog.cs [hunk 2]
```diff
@@ -567,130 +514,176 @@ private void SetupActivationInstance(ActivationData result, string grainType, st
...
+                switch (initStage)
+                {
+                    case ActivationInitializationStage.Register: // failed to RegisterActivationInGrainDirectory
+
+                        // Failure!! Could it be that this grain uses single activation placement, and there already was an activation?
+                        activation.ForwardingAddress = registrationResult.ExistingActivationAddress;
+                        if (activation.ForwardingAddress != null)
+                        {
+                            CounterStatistic
+                                .FindOrCreate(StatisticNames.CATALOG_ACTIVATION_DUPLICATE_ACTIVATIONS)
```
Comment (jdom) [inline src/OrleansRuntime/Catalog/Catalog.cs]: Should the `CATALOG_ACTIVATION_DUPLICATE_ACTIVATIONS` also be renamed? it's scary if you see that number go up, but we concluded this is harmless under normal operation, right?

File: src/OrleansRuntime/Catalog/Catalog.cs [hunk 3]
```diff
@@ -567,130 +514,176 @@ private void SetupActivationInstance(ActivationData result, string grainType, st
...
+                                        "{3}" +
+                                        "Full activation address is {4}. We have {5} messages to forward.",
+                                        address,
+                                        activation.ForwardingAddress,
+                                        activation.GrainInstanceType,
+                                        primary != null
+                                            ? "Primary Directory partition for this grain is " + primary + ". "
+                                            : String.Empty,
+                                        address.ToFullString(),
+                                        activation.WaitingCount);
```
Comment (jdom) [inline src/OrleansRuntime/Catalog/Catalog.cs]: probably interpolating this string will be more readable, right?

File: src/OrleansRuntime/Catalog/Catalog.cs [hunk 4]
```diff
@@ -567,130 +514,176 @@ private void SetupActivationInstance(ActivationData result, string grainType, st
...
-                                logger.Warn(ErrorCode.Runtime_Error_100064,
-                                    String.Format("Failed to RegisterActivationInGrainDirectory for {0}.",
-                                        activation), ex);
-                                // Need to undo the registration we just did earlier
-                                if (activation.IsUsingGrainDirectory)
+                                else if (logger.IsVerbose)
                                 {
-                                    scheduler.RunOrQueueTask(() => directory.UnregisterAsync(address, UnregistrationCause.Force),
-                                        SchedulingContext).Ignore();
+                                    logger.Verbose(ErrorCode.Catalog_DuplicateActivation, logMsg);
```
Comment (jdom) [inline src/OrleansRuntime/Catalog/Catalog.cs]: no need to check for IsVerbose, since you are not formatting strings or incurring any penalty by just calling `logger.Verbose`  directly, which already checks for IsVerbose

File: src/OrleansRuntime/Catalog/Catalog.cs (hunk 1 above)
Comment (ReubenBond) [inline src/OrleansRuntime/Catalog/Catalog.cs]: I prefered to keep it in one place, but I can do both if you prefer.

File: src/OrleansRuntime/Catalog/Catalog.cs (hunk 2 above)
Comment (ReubenBond) [inline src/OrleansRuntime/Catalog/Catalog.cs]: This is harmless, yes - maybe it bears renaming

**Comment by ReubenBond** [comment]
@dotnet-bot test netstandard-win-functional

File: src/OrleansRuntime/Catalog/Catalog.cs (hunk 2 above)
Comment (ReubenBond) [inline src/OrleansRuntime/Catalog/Catalog.cs]: `public static readonly StatisticName CATALOG_ACTIVATION_DUPLICATE_ACTIVATIONS                               = new StatisticName("Catalog.Activation.DuplicateActivations");`

Potential names? `Catalog.Activation.RegistrationRaces`, `Catalog.Activation.ConcurrentRegistrationAttempts`? I prefer the second one, it's precise.

**Comment by ReubenBond** [comment]
@dotnet-bot test netstandard-win-functional

File: src/OrleansRuntime/Catalog/Catalog.cs (hunk 2 above)
Comment (ReubenBond) [inline src/OrleansRuntime/Catalog/Catalog.cs]: If the latter is chosen, we should add a line to the release log:
> Renamed the `Catalog.Activation.DuplicateActivations` counter to `Catalog.Activation.ConcurrentRegistrationAttempts` to more accurately reflect what it tracks and its benign nature.

File: src/Orleans/Statistics/StatisticNames.cs [hunk 5]
```diff
@@ -219,7 +219,7 @@ internal class StatisticNames
         public static readonly StatisticName CATALOG_ACTIVATION_SHUTDOWN_VIA_DIRECT_SHUTDOWN                        = new StatisticName("Catalog.Activation.Shutdown.ViaDirectShutdown");
         public static readonly StatisticName CATALOG_ACTIVATION_SHUTDOWN_VIA_DEACTIVATE_STUCK_ACTIVATION            = new StatisticName("Catalog.Activation.Shutdown.ViaDeactivateStuckActivation");
         public static readonly StatisticName CATALOG_ACTIVATION_NON_EXISTENT_ACTIVATIONS                            = new StatisticName("Catalog.Activation.NonExistentActivations");
-        public static readonly StatisticName CATALOG_ACTIVATION_DUPLICATE_ACTIVATIONS                               = new StatisticName("Catalog.Activation.DuplicateActivations");
+        public static readonly StatisticName CATALOG_ACTIVATION_CONCURRENT_REGISTRATION_ATTEMPTS                    = new StatisticName("Catalog.Activation.ConcurrentRegistrationAttempts");
```
Comment (jdom) [inline src/Orleans/Statistics/StatisticNames.cs]: @jason-bragg / @sergeybykov any concerns with this rename?
(do we need to put it in release notes?)

Comment (ReubenBond) [inline src/Orleans/Statistics/StatisticNames.cs]: My comment got swallowed by the diff, but:

"
If the latter is chosen, we should add a line to the release log:
> Renamed the `Catalog.Activation.DuplicateActivations` counter to `Catalog.Activation.ConcurrentRegistrationAttempts` to more accurately reflect what it tracks and its benign nature.

"

IMO it's best to mention it

Comment (sergeybykov) [inline src/Orleans/Statistics/StatisticNames.cs]: I think it's fine. It's never been a critical thing to monitor. So I don't expect it to be a problem.
