### PR TITLE
Fix codegen warnings in source tree

### LINKED ISSUE #5255: Fix build warnings caused by new codegen in test tree
The warning introduced in #5031 shows up in our build logs because some test state classes inherit from `Dictionary<,>`

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #5255

Also fixes the source line when the warning is emitted so that it will show correctly in VS/tooling

### CODE REVIEW

File: src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs [hunk 1]
```diff
@@ -495,46 +495,63 @@ private static List<FieldInfoMember> GetFields(WellKnownTypes wellKnownTypes, Se
...
+                var hasUnsupportedRefAsmBase = false;
+                var referenceAssemblyHasFields = false;
+                var baseType = type.BaseType;
+                while (baseType != null &&
+                       !baseType.Equals(wellKnownTypes.Object) &&
+                       !baseType.Equals(wellKnownTypes.Attribute))
                 {
-                    if (hasReferenceAssemblyBase) referenceAssemblyHasFields = true;
-                    if (ShouldSerializeField(wellKnownTypes, field))
+                    if (!hasUnsupportedRefAsmBase && baseType.ContainingAssembly.HasAttribute("ReferenceAssemblyAttribute") && !IsSupportedRefAsmType(baseType)) hasUnsupportedRefAsmBase = true;
```
Comment (sergeybykov) [inline src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs]: This line is very long and it's not easy to see that `hasUnsupportedRefAsmBase` gets mutated at the end of it. Better split into at least two lines for readability.

File: src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs [hunk 2]
```diff
@@ -495,46 +495,63 @@ private static List<FieldInfoMember> GetFields(WellKnownTypes wellKnownTypes, Se
...
+                    logger.LogWarning(
+                        $"{fileLocation}warning ORL1001: Type {type} has a base type which belongs to a reference assembly. Serializer generation for this type may not include important base type fields.");
                 }
 
-                logger.LogWarning(
-                    $"{fileLocation}Warning: Type {type} has a base type which belongs to a reference assembly. Serializer generation for this type may not include important base type fields.");
+                bool IsSupportedRefAsmType(INamedTypeSymbol t)
+                {
+                    INamedTypeSymbol baseDefinition;
+                    if (t.IsGenericType && !t.IsUnboundGenericType) baseDefinition = t.ConstructUnboundGenericType().OriginalDefinition;
```
Comment (sergeybykov) [inline src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs]: Same issue here.

**Comment by ReubenBond** [comment]
@dotnet-bot test bvt
