### PR TITLE
Fix stack deserialization order

### LINKED ISSUE #8766: Serialization: Stack<T> is deserialized in reversed order
Consider following example:
```cs
public class MyGrain : IMyGrain
{
    public Task<Stack<int>> GetStack()
    {
        var stack = new Stack<int>();
        stack.Push(1);
        stack.Push(2);
        stack.Push(3);
        stack.Push(4);
        return Task.FromResult(stack);
    }
}
```
And the calling code:
```cs
var stack = await myGrain.GetStack();
var value = stack.Pop(); // returns 1
```

Here in `StackCodec` during deserealization process values from original stack are just pushed to the new stack what makes the order to be reversed.
https://github.com/dotnet/orleans/blob/cd09126368aeb9e5ede05ba6618a5b538e987722/src/Orleans.Serialization/Codecs/StackCodec.cs#L97

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #8766

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8768)

### CODE REVIEW

File: src/Orleans.Serialization/Codecs/StackCodec.cs [hunk 1]
```diff
@@ -7,165 +7,166 @@
...
-                {
+                case 0:
+                    var length = (int)UInt32Codec.ReadValue(ref reader, header);
+                    if (length > 10240 && length > reader.Length)
+                    {
+                        ThrowInvalidSizeException(length);
+                    }
+
+                    array = new T[length];
+                    i = length - 1;
```
Comment (ReubenBond) [inline src/Orleans.Serialization/Codecs/StackCodec.cs:90]: The crux of the fix is to populate an array in reverse order and then initialize the stack with it. Stack does not offer a way to get/modify the underlying array directly or enumerate in reverse order.
