### PR TITLE
Identify F# single case discriminated unions as SumType

### LINKED ISSUE #8715: F# single case discriminated unions not serialized correctly
We are upgrading to Orleans 7 in a project using F#. When using single case discriminated unions as arguments to a grain interface, the serializer fails to serialize the argument correctly.

The [attached solution](https://github.com/dotnet/orleans/files/13317800/FSharpHelloWorld.zip), based on the [F#-sample](https://github.com/dotnet/samples/tree/main/orleans/FSharpHelloWorld), reproduces the issue. When running the solution, the value of `SingleCaseDiscriminatedUnion.Case` is `null` when received in `HelloGrain`.

_This is the single case discriminated union we're trying to serialize._
```fsharp
[<GenerateSerializer>]
type SingleCaseDiscriminatedUnion =
    | Case of string // the string is null when received in the grain
``` 

_This is the grain where we're using the single case discriminated union._
```fsharp
type HelloGrain() = 
    inherit Orleans.Grain()
    interface IHelloGrain with
        override this.SayHello(message) =
            let greeting = SingleCaseDiscriminatedUnion.value message // greeting is now null
            ValueTask.FromResult greeting
```

Including a second case in the discriminated union makes the test work.

Related issue #8255

### PR DESCRIPTION
**Pull request by gfix**
Unlike discriminated unions with more than two cases, single case discriminated unions do not inherit from an abstract base class, thus, for single case discriminated unions we need to look for the CompilationMappingAttribute on the type itself.

Single case discriminated unions do have a declared instance member named "Item", so the `FSharpUnionCaseTypeDescription` [correctly identifies this](https://github.com/dotnet/orleans/blob/main/src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs#L110).

Fixes #8715

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8739)

### CODE REVIEW

**Comment by gfix** [comment]
@dotnet-policy-service agree company="NRK"

File: src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs [hunk 1]
```diff
@@ -24,7 +24,16 @@ public static bool IsUnionCase(LibraryTypes libraryTypes, INamedTypeSymbol symbo
...
-            if (!baseType.GetAttributes(compilationAttributeType, out var compilationAttributes) || compilationAttributes.Length == 0)
+            INamedTypeSymbol sumTypeCandidate;
+            if (symbol.GetAttributes(compilationAttributeType, out var compilationAttributes) && compilationAttributes.Length > 0)
+            {
+                sumTypeCandidate = symbol;
+            }
+            else if (baseType.GetAttributes(compilationAttributeType, out compilationAttributes) && compilationAttributes.Length > 0)
+            {
+                sumTypeCandidate = baseType;
+            }
```
Comment (ReubenBond) [inline src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs:35]: Do we ever need to worry about deeper inheritance chains than this?

**Review by ReubenBond — APPROVED** [review]

File: src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs (hunk 1 above)
Comment (gfix) [reply src/Orleans.CodeGenerator/SyntaxGeneration/FSharpUtils.cs:35]: Not that I know of. There is however an issue with DUs of 4 cases or more, but not due to inheritance. I will open separate issue for that.
