### PR TITLE
PVS-Studio: Fixes confusing if-else statement.

### LINKED ISSUE #1394: PVS-Studio: Confusing if-else statement in Orleans.Interner.InternCacheCleanupTimerCallback method
It's hard to read and understand what this code is suppose to do.

**V3033 It is possible that this 'else' branch must apply to the previous 'if' statement. Orleans Interner.cs 251**

```
        private void InternCacheCleanupTimerCallback(object state)
        {
         ...

            long numRemoved = numEntries - internCache.Count;
            if (numRemoved>0)
                if (logger.IsVerbose) logger.Verbose(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
            else
                if (logger.IsVerbose2) logger.Verbose2(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
        }

```

### PR DESCRIPTION
**Pull request by gabikliot**
Fixes #1394.

### CODE REVIEW

File: src/Orleans/IDs/Interner.cs [hunk 1]
```diff
@@ -246,10 +246,14 @@ private void InternCacheCleanupTimerCallback(object state)
...
             }
             long numRemoved = numEntries - internCache.Count;
-            if (numRemoved>0)
+            if (numRemoved > 0)
+            {
                 if (logger.IsVerbose) logger.Verbose(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
+            }
             else
+            {
                 if (logger.IsVerbose2) logger.Verbose2(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
```
Comment (dVakulen) [inline src/Orleans/IDs/Interner.cs]: I think this statement was meant to be executed if condition logger.IsVerbose is false, and not if numRemoved > 0 is false. Also it will cause merge conflict with https://github.com/dotnet/orleans/pull/1444/files

Comment (jdom) [inline src/Orleans/IDs/Interner.cs]: hmmm, not sure @dVakulen since that wouldn't make a lot of sense. If IsVerbose is false, then IsVerbose2 will certainly be false. I think that if numRemoved == 0 it was logging as Verbose2

**Comment by jdom** [comment]
@dotnet-bot test this please

File: src/Orleans/IDs/Interner.cs (hunk 1 above)
Comment (gabikliot) [inline src/Orleans/IDs/Interner.cs]: I think the intention is like I coded it. If something was removed, log at Verbose, if nothing was removed (less interesting event), log at Verbose2. The `if(logger.IsVerbose)` is there instead of compile time #IFDEF.

Comment (dVakulen) [inline src/Orleans/IDs/Interner.cs]: I see. Before the fix the `Verbose2` log statement was never called.
