### PR TITLE
PVS-Studio: switch statement

### LINKED ISSUE #1392: PVS-Studio: ToString override in Runtime.Message - switch statement doesn't cover all values
ToString override for Orleans.Runtime.Message doesnt cover all enum values.
Overall code looks a bit dangerous with no defaults\fallbacks

**V3002 The switch statement does not cover all values of the 'ResponseTypes' enum: Success. Message.cs 995**

```
 public override string ToString()
        {
            string response = String.Empty;
            if (Direction == Directions.Response)
            {
                switch (Result)
                {
                    case ResponseTypes.Error:
                        response = "Error ";
                        break;

                    case ResponseTypes.Rejection:
                        response = string.Format("{0} Rejection (info: {1}) ", RejectionType, RejectionInfo);
                        break;
                }
            }
```

### PR DESCRIPTION
**Pull request by gabikliot**
Fixes #1392.

### CODE REVIEW

File: src/Orleans/IDs/Interner.cs [hunk 1]
```diff
@@ -246,10 +246,14 @@ private void InternCacheCleanupTimerCallback(object state)
...
             }
             long numRemoved = numEntries - internCache.Count;
-            if (numRemoved>0)
+            if (numRemoved > 0)
+            {
                 if (logger.IsVerbose) logger.Verbose(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
+            }
             else
+            {
                 if (logger.IsVerbose2) logger.Verbose2(ErrorCode.Runtime_Error_100296, "Removed {0} / {1} unused {2} entries in {3}", numRemoved, numEntries, internCacheName, clock.Elapsed);
```
Comment (dVakulen) [inline src/Orleans/IDs/Interner.cs]: I think this statement was meant to be executed if condition `logger.IsVerbose` is false, and not if `numRemoved > 0` is false.

**Comment by jdom** [comment]
@dotnet-bot test this please

**Comment by gabikliot** [comment]
Removed redundant commit.
