### PR TITLE
Fix #1869. Grain Extensions + method interception should function correctly

### LINKED ISSUE #1869: Global Serverside interceptors throws KeyNotFound exception
Hi, I have implemented the following global serverside interceptor. 

```
public class ServerSideInterceptor : IBootstrapProvider
    {
        public Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            providerRuntime.SetInvokeInterceptor((method, request, grain, invoker) =>
            {
                Debug.WriteLine("Doing some magic here");
                return invoker.Invoke(grain, request);

            });
            return Task.FromResult(0);
        }

        public Task Close()
        {
            return Task.FromResult(0);
        }

        public string Name { get; }
    }
```

This works well when you have grains calling other grains, but as soon as you have a grain that subscribes to a stream then a `KeyNotFoundException` gets thrown. If you just call the grain normally without using streams everything works 100%.

Below is an example of the grain subscribing to the stream that is causing the exception to be thrown

```
[ImplicitStreamSubscription("TestStream")]
    public class SubGrain : Grain, ISubGrain , IAsyncObserver<Guid> 
    {
        private StreamSubscriptionHandle<Guid> _subscriptionHandle;

        public override async Task OnActivateAsync()
        {
            var streamProvider = GetStreamProvider("SMSProvider");
            var incomingStream = streamProvider.GetStream<Guid>(this.GetPrimaryKey(), "TestStream");
            _subscriptionHandle = await incomingStream.SubscribeAsync((IAsyncObserver<Guid>)this);
            await base.OnActivateAsync();
        }

        public Task SayHallo()
        {
            return TaskDone.Done;
        }

         public async Task OnNextAsync(Guid item, StreamSequenceToken token = null)
        {
            Console.WriteLine($"Hallo from Grain : {this.GetPrimaryKey()}");
            var t = GrainFactory.GetGrain<TestHost.Grains.IFooGrain>(item);
            await t.KeepAlive();
        }

        public Task OnCompletedAsync()
        {
            return TaskDone.Done;
        }

        public Task OnErrorAsync(Exception ex)
        {
            return TaskDone.Done;
        }

        public Task<FilterRow[]> GetFilters()
        {
            return Task.FromResult(new FilterRow[] {});
        }
    }
```

### PR DESCRIPTION
**Pull request by ReubenBond**
This PR addresses #1869, allowing method interception to function correctly when grain extensions (such as streams) are invoked.

Additionally, comments and naming were (hopefully) improved in the relevant code.

The approach is to give `ActivationData.ExtensionInvoker` a new interface, `IGrainExtensionMap`, which can then be queried when creating the `InterceptedMethodInvoker` for that extension. I've marked the crux of the change with a comment in the change list.

cc @gabikliot - I'd like your opinion on my approach here.

### CODE REVIEW

File: src/Orleans/Core/InterceptedMethodInvokerCache.cs [hunk 1]
```diff
@@ -30,18 +48,44 @@ public InterceptedMethodInvoker GetInterceptedMethodInvoker(Type implementationT
...
+        /// <param name="invoker">The invoker.</param>
+        /// <returns>A new <see cref="InterceptedMethodInvoker"/> for the provided values.</returns>
+        private static InterceptedMethodInvoker CreateInterceptedMethodInvoker(
+            Type implementationType,
+            int interfaceId,
+            IGrainMethodInvoker invoker)
+        {
+            // If a grain extension is being invoked, the implementation map must match the methods on the extension
+            // and not the grain implementation.
+            var extensionMap = invoker as IGrainExtensionMap;
```
Comment (ReubenBond) [inline src/Orleans/Core/InterceptedMethodInvokerCache.cs]: This is the functional core of the fix: if the invoker is the extension invoker, then we retrieve the extension class and get the implementation map for that class instead of the grain class.

File: src/Orleans/CodeGeneration/IGrainMethodInvoker.cs [hunk 2]
```diff
@@ -35,4 +35,20 @@ public interface IGrainExtensionMethodInvoker : IGrainMethodInvoker
         /// <returns>Value promise for the result of the method invoke.</returns>
         Task<object> Invoke(IGrainExtension extension, InvokeMethodRequest request);
     }
+
+    /// <summary>
+    /// Methods for querying a collection of grain extensions.
+    /// </summary>
+    public interface IGrainExtensionMap
```
Comment (ReubenBond) [inline src/Orleans/CodeGeneration/IGrainMethodInvoker.cs]: This is the new interface. `ActivationData.ExtensionInvoker` implements it.

**Comment by ReubenBond** [comment]
@Dewaldf mentioned in chat that this fix solves the cited issue.

File: src/OrleansRuntime/Core/InsideRuntimeClient.cs [hunk 3]
```diff
@@ -364,35 +364,50 @@ public void SniffIncomingMessage(Message message)
...
-                            var runtime = SiloProviderRuntime.Instance;
-                            resultObject =
-                                await runtime.CallInvokeInterceptor(methodInfo, request, target, implementationInvoker);
+                            // As a minor optimization, only pass the intercepted invoker if there is a grain-level
+                            // interceptor.
+                            resultTask = SiloProviderRuntime.Instance.CallInvokeInterceptor(
+                                methodInfo,
+                                request,
+                                target,
+                                grainHasInterceptor ? interceptedInvoker : invoker);
```
Comment (gabikliot) [inline src/OrleansRuntime/Core/InsideRuntimeClient.cs]: I don t understand this logic. why we sometimes call interceptedInvoker and sometimes invoker.
is it the case that you call both global and then per grain interceptor and then the actual call? 3 step call? Also, confused with the global if and then sub case if else.

Comment (ReubenBond) [inline src/OrleansRuntime/Core/InsideRuntimeClient.cs]: My apologies for the confusion. I'll try to explain and then perhaps you can suggest a change.

* `invoker` is the plain-old (probably code-genned) `IGrainMethodInvoker`
* interceptedInvoker is an `IGrainMethodInvoker` which *wraps* `invoker`, passing all calls through `intercepted.Invoke` (note: `intercepted == target`, it's just cast to `IGrainInvokeInterceptor`)
* `SiloProviderRuntime.Instance.CallInvokeInterceptor` is the silo-wide interceptor.

We can have 4 cases, contingent on the presence of silo-level & grain-level interceptors.

 grain-level | silo-level | result | reason
---------------|------------|---------|---
NO |  NO | `invoker.Invoke()` | no interception at all
YES | NO  | `intercepted.Invoke()` | call the grain's `Invoke` method passing in `MethodInfo`
NO  | YES | `CallInvokeInterceptor(invoker)` | call the silo-level interceptor only
YES | YES | `CallInvokeInterceptor(interceptedInvoker)` | call the silo-level interceptor, passing an `IGrainMethodInvoker` which passes all calls through the grain-level interceptor

We use `intercepted` directly in the grain-level-only case instead of `interceptedInvoker` because the latter wraps the former to make it conform to the `IGrainMethodInvoker` interface and we don't need that wrapper. `intercepted` is the grain and implements `IGrainInvokeInterceptor` which has an identical method, `Invoke`, which takes one extra argument, `MethodInfo`.

Changes I could make (you may have more):
1. rename some of these variables & improve comments
2. split out the `MethodInfo` cache from `InterceptedMethodInvokerCache` so that there are two classes instead: one class which caches `MethodInfo`s and one which caches `InterceptedMethodInvoker`s
3. try to remove some if-statements/conditionals and always call a wrapped invoker (using a default one if no interceptor is specified at each level)

What are your thoughts?

**Comment by ReubenBond** [comment]
In addition to the line comment, would it be easier to understand if I extracted a new 'InvokeInner` method out like so?
```c#
private Task<object> InvokeInner(IAddressable target, InvokeMethodRequest request, IGrainMethodInvoker invoker)
{
    // If the target has a grain-level interceptor or there is a silo-level interceptor, intercept the
    // call.
    var siloWideInterceptor = SiloProviderRuntime.Instance.GetInvokeInterceptor();
    var grainWithInterceptor = target as IGrainInvokeInterceptor;
            
    // Silo-wide interceptors do not operate on system targets.
    var hasSiloWideInterceptor = siloWideInterceptor != null && target is IGrain;
    var hasGrainLevelInterceptor = grainWithInterceptor != null;
            
    if (!hasGrainLevelInterceptor && !hasSiloWideInterceptor)
    {
        // The call is not intercepted at either the silo or the grain level, so call the invoker
        // directly.
        return invoker.Invoke(target, request);
    }

    // Get an invoker which delegates to the grain's IGrainInvocationInterceptor implementation.
    // If the grain does not implement IGrainInvocationInterceptor, then the invoker simply delegates
    // calls to the provided invoker.
    var interceptedMethodInvoker = interceptedMethodInvokerCache.GetOrCreate(
        target.GetType(),
        request.InterfaceId,
        invoker);
    var methodInfo = interceptedMethodInvoker.GetMethodInfo(request.MethodId);
    if (hasSiloWideInterceptor)
    {
        // There is a silo-level interceptor and possibly a grain-level interceptor.
        // As a minor optimization, only pass the intercepted invoker if there is a grain-level
        // interceptor.
        return siloWideInterceptor(
            methodInfo,
            request,
            (IGrain)target,
            hasGrainLevelInterceptor ? interceptedMethodInvoker : invoker);
    }

    // The grain has an invoke method, but there is no silo-wide interceptor.
    return grainWithInterceptor.Invoke(methodInfo, request, invoker);
}
```

**Comment by gabikliot** [comment]
I think if we move all the code from InsideRuntimeClient about invoke into a separate method, or helper class, that does all those cases and hides all the interceptors and in this class you add all the above explanations, it would already be a big step forward. Basically, InvokeInner just name it InvokeWithInterceptors.

As for the table above: why do we need "interceptedInvoker is an IGrainMethodInvoker which wraps invoker, passing all calls through intercepted.Invoke". Why do we need the wrapping?

**Comment by ReubenBond** [comment]
We need the wrapping because of the difference between the two interfaces:
`invoker`:
```C#
public interface IGrainMethodInvoker
{
    int InterfaceId { get; }
    Task<object> Invoke(IAddressable grain, InvokeMethodRequest request);
}
```

`intercepted` (i.e, the underlying grain):
```C#
public interface IGrainInvokeInterceptor
{
    Task<object> Invoke(MethodInfo method, InvokeMethodRequest request, IGrainMethodInvoker invoker);
}
```

Silo-level interceptors are called first, then grain-level, then inbuilt.
Silo-level interceptor takes an `IGrainMethodInvoker`, but the grain implements `IGrainInvokeInterceptor`, so the wrapper is needed currently.

Does that sound reasonable, or do you think we should change the code?

I'll rename the extracted method to InvokeWithInterceptors and push an update.

**Comment by gabikliot** [comment]
Yes, it does sound reasonable.
I think there is an opportunity to revisit the whole invokers story, now that we added the extra complexity of 2 level interceptors, plus the original interceptor is also non trivial, as it handles extensions. Maybe we can get rid of the wrapper as well.
But that probably goes beyond the scope of this PR, which was first to fix #1869.
As a 2nd step we may want to revisit the bigger picture, but I am OK with this PR as is.

**Comment by sergeybykov** [comment]
@gabikliot So this one is ready to merge, right?

**Comment by gabikliot** [comment]
Yes, it is.

**Comment by sergeybykov** [comment]
Looks like this broke GrainMethodInterceptionTest. Not sure if this is a test issue.
